name: inventory_app
description: "A simple inventory application."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
 
version: 1.0.0+1

environment:
  sdk: ^3.8.0
 
dependencies:
  flutter:
    sdk: flutter 
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.0.14
  path: ^1.8.0
  qr_code_scanner_plus: ^2.0.10+1
  sqflite: ^2.4.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  excel: ^4.0.6
  file_saver: ^0.2.14
  flutter_launcher_icons: ^0.14.3
  file_picker: ^10.1.9 
  mobile_scanner: ^7.0.0
  sqflite_common_ffi: ^2.3.5
  flutter_localization: ^0.3.2 
  intl: ^0.20.2
  url_launcher: ^6.3.1
  pie_chart: ^5.4.0
  dynamic_color: ^1.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^6.0.0
  dartdoc: ^8.3.4

flutter_launcher_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true  
  linux: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logo.png"
 
flutter:
 
  uses-material-design: true
  generate: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
